/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as DoctorPortalRouteImport } from './routes/doctor-portal'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as MonitoringRouteImport } from './routes/monitoring'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPortalRoute = DoctorPortalRouteImport.update({
  id: '/doctor-portal',
  path: '/doctor-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/doctor-portal': typeof DoctorPortalRoute
  '/follow-ups': typeof FollowUpsRoute
  '/monitoring': typeof MonitoringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/doctor-portal': typeof DoctorPortalRoute
  '/follow-ups': typeof FollowUpsRoute
  '/monitoring': typeof MonitoringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/doctor-portal': typeof DoctorPortalRoute
  '/follow-ups': typeof FollowUpsRoute
  '/monitoring': typeof MonitoringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/architecture' | '/doctor-portal' | '/follow-ups' | '/monitoring'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/architecture' | '/doctor-portal' | '/follow-ups' | '/monitoring'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/doctor-portal'
    | '/follow-ups'
    | '/monitoring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DoctorPortalRoute: typeof DoctorPortalRoute
  FollowUpsRoute: typeof FollowUpsRoute
  MonitoringRoute: typeof MonitoringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-portal': {
      id: '/doctor-portal'
      path: '/doctor-portal'
      fullPath: '/doctor-portal'
      preLoaderRoute: typeof DoctorPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  DoctorPortalRoute: DoctorPortalRoute,
  FollowUpsRoute: FollowUpsRoute,
  MonitoringRoute: MonitoringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
