import { Plant, CareTask, CareRecord } from '../types';
import { formatDate, addDays } from './plantService';

export const getSamplePlantsData = (userId: string): { plants: Plant[]; tasks: CareTask[]; records: CareRecord[] } => {
  const todayStr = formatDate(new Date());

  const p1Id = 'sample-plant-1';
  const p2Id = 'sample-plant-2';
  const p3Id = 'sample-plant-3';
  const p4Id = 'sample-plant-4';

  const plants: Plant[] = [
    {
      id: p1Id,
      userId,
      name: 'Money Plant',
      species: 'Epipremnum aureum',
      environment: 'indoor',
      location: 'Living Room Shelf',
      lastWatered: addDays(todayStr, -6),
      wateringFrequency: 7,
      nextWateringDate: addDays(todayStr, 1),
      status: 'Healthy',
      notes: 'Loves bright indirect sunlight. Allow top 2 inches of soil to dry between waterings.',
      isDemo: true,
      createdAt: addDays(todayStr, -30),
    },
    {
      id: p2Id,
      userId,
      name: 'Tulsi',
      species: 'Ocimum tenuiflorum',
      environment: 'outdoor',
      location: 'Balcony Garden',
      lastWatered: addDays(todayStr, -2),
      wateringFrequency: 2,
      nextWateringDate: todayStr,
      status: 'Care Due',
      notes: 'Holy basil. Requires 4-6 hours of direct morning sun. Keep soil evenly moist.',
      isDemo: true,
      createdAt: addDays(todayStr, -45),
    },
    {
      id: p3Id,
      userId,
      name: 'Aloe Vera',
      species: 'Aloe barbadensis miller',
      environment: 'indoor',
      location: 'Kitchen Window Sill',
      lastWatered: addDays(todayStr, -15),
      wateringFrequency: 12,
      nextWateringDate: addDays(todayStr, -3),
      status: 'Overdue',
      notes: 'Succulent with healing gel. Water deeply but infrequently; highly drought resistant.',
      isDemo: true,
      createdAt: addDays(todayStr, -60),
    },
    {
      id: p4Id,
      userId,
      name: 'Snake Plant',
      species: 'Sansevieria trifasciata',
      environment: 'indoor',
      location: 'Bedroom Corner',
      lastWatered: addDays(todayStr, -5),
      wateringFrequency: 14,
      nextWateringDate: addDays(todayStr, 9),
      status: 'Healthy',
      notes: 'Top air purifier. Very hardy and tolerates low light. Prone to root rot if overwatered.',
      isDemo: true,
      createdAt: addDays(todayStr, -90),
    },
  ];

  const tasks: CareTask[] = [
    {
      id: 'task-1',
      userId,
      plantId: p2Id,
      plantName: 'Tulsi',
      taskType: 'Water',
      dueDate: todayStr,
      status: 'pending',
      notes: 'Morning watering recommended before midday heat.',
      isDemo: true,
      createdAt: addDays(todayStr, -1),
    },
    {
      id: 'task-2',
      userId,
      plantId: p1Id,
      plantName: 'Money Plant',
      taskType: 'Check Soil',
      dueDate: todayStr,
      status: 'pending',
      notes: 'Check if top 2 inches of soil feel dry.',
      isDemo: true,
      createdAt: addDays(todayStr, -1),
    },
    {
      id: 'task-3',
      userId,
      plantId: p3Id,
      plantName: 'Aloe Vera',
      taskType: 'Water',
      dueDate: addDays(todayStr, -3),
      status: 'pending',
      notes: 'Overdue! Check soil moisture and give deep soak if dry.',
      isDemo: true,
      createdAt: addDays(todayStr, -4),
    },
    {
      id: 'task-4',
      userId,
      plantId: p1Id,
      plantName: 'Money Plant',
      taskType: 'Water',
      dueDate: addDays(todayStr, 1),
      status: 'pending',
      notes: 'Scheduled regular weekly watering.',
      isDemo: true,
      createdAt: addDays(todayStr, -2),
    },
    {
      id: 'task-5',
      userId,
      plantId: p4Id,
      plantName: 'Snake Plant',
      taskType: 'Check Soil',
      dueDate: addDays(todayStr, 3),
      status: 'pending',
      notes: 'Ensure soil is completely dry before upcoming water cycle.',
      isDemo: true,
      createdAt: addDays(todayStr, -1),
    },
  ];

  const records: CareRecord[] = [
    {
      id: 'rec-1',
      userId,
      plantId: p1Id,
      plantName: 'Money Plant',
      action: 'Watered',
      date: addDays(todayStr, -6),
      notes: 'Filtered water applied. Foliage misted lightly.',
      isDemo: true,
      createdAt: addDays(todayStr, -6),
    },
    {
      id: 'rec-2',
      userId,
      plantId: p2Id,
      plantName: 'Tulsi',
      action: 'Watered',
      date: addDays(todayStr, -2),
      notes: 'Routine morning watering.',
      isDemo: true,
      createdAt: addDays(todayStr, -2),
    },
    {
      id: 'rec-3',
      userId,
      plantId: p3Id,
      plantName: 'Aloe Vera',
      action: 'Checked Soil',
      date: addDays(todayStr, -8),
      notes: 'Soil was slightly moist, deferred watering.',
      isDemo: true,
      createdAt: addDays(todayStr, -8),
    },
    {
      id: 'rec-4',
      userId,
      plantId: p4Id,
      plantName: 'Snake Plant',
      action: 'Watered',
      date: addDays(todayStr, -5),
      notes: 'Thorough soak and drain.',
      isDemo: true,
      createdAt: addDays(todayStr, -5),
    },
    {
      id: 'rec-5',
      userId,
      plantId: p1Id,
      plantName: 'Money Plant',
      action: 'Pruned',
      date: addDays(todayStr, -14),
      notes: 'Trimmed two yellowing lower leaves.',
      isDemo: true,
      createdAt: addDays(todayStr, -14),
    },
  ];

  return { plants, tasks, records };
};
