/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAssistantRouteImport } from './routes/_authenticated/app.assistant'
import { Route as AuthenticatedAppCompareRouteImport } from './routes/_authenticated/app.compare'
import { Route as AuthenticatedAppGraphRouteImport } from './routes/_authenticated/app.graph'
import { Route as AuthenticatedAppNotesRouteImport } from './routes/_authenticated/app.notes'
import { Route as AuthenticatedAppSearchRouteImport } from './routes/_authenticated/app.search'
import { Route as AuthenticatedAppUploadRouteImport } from './routes/_authenticated/app.upload'
import { Route as AuthenticatedAppCollectionsIndexRouteImport } from './routes/_authenticated/app.collections.index'
import { Route as AuthenticatedAppCollectionsIdRouteImport } from './routes/_authenticated/app.collections.$id'
import { Route as AuthenticatedAppDocumentsIndexRouteImport } from './routes/_authenticated/app.documents.index'
import { Route as AuthenticatedAppDocumentsIdRouteImport } from './routes/_authenticated/app.documents.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAssistantRoute =
  AuthenticatedAppAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCompareRoute = AuthenticatedAppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppGraphRoute = AuthenticatedAppGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotesRoute = AuthenticatedAppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSearchRoute = AuthenticatedAppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppUploadRoute = AuthenticatedAppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCollectionsIndexRoute =
  AuthenticatedAppCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCollectionsIdRoute =
  AuthenticatedAppCollectionsIdRouteImport.update({
    id: '/collections/$id',
    path: '/collections/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentsIndexRoute =
  AuthenticatedAppDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentsIdRoute =
  AuthenticatedAppDocumentsIdRouteImport.update({
    id: '/documents/$id',
    path: '/documents/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/compare': typeof AuthenticatedAppCompareRoute
  '/app/graph': typeof AuthenticatedAppGraphRoute
  '/app/notes': typeof AuthenticatedAppNotesRoute
  '/app/search': typeof AuthenticatedAppSearchRoute
  '/app/upload': typeof AuthenticatedAppUploadRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/collections/$id': typeof AuthenticatedAppCollectionsIdRoute
  '/app/documents/$id': typeof AuthenticatedAppDocumentsIdRoute
  '/app/collections/': typeof AuthenticatedAppCollectionsIndexRoute
  '/app/documents/': typeof AuthenticatedAppDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/compare': typeof AuthenticatedAppCompareRoute
  '/app/graph': typeof AuthenticatedAppGraphRoute
  '/app/notes': typeof AuthenticatedAppNotesRoute
  '/app/search': typeof AuthenticatedAppSearchRoute
  '/app/upload': typeof AuthenticatedAppUploadRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/collections/$id': typeof AuthenticatedAppCollectionsIdRoute
  '/app/documents/$id': typeof AuthenticatedAppDocumentsIdRoute
  '/app/collections': typeof AuthenticatedAppCollectionsIndexRoute
  '/app/documents': typeof AuthenticatedAppDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/_authenticated/app/compare': typeof AuthenticatedAppCompareRoute
  '/_authenticated/app/graph': typeof AuthenticatedAppGraphRoute
  '/_authenticated/app/notes': typeof AuthenticatedAppNotesRoute
  '/_authenticated/app/search': typeof AuthenticatedAppSearchRoute
  '/_authenticated/app/upload': typeof AuthenticatedAppUploadRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/collections/$id': typeof AuthenticatedAppCollectionsIdRoute
  '/_authenticated/app/documents/$id': typeof AuthenticatedAppDocumentsIdRoute
  '/_authenticated/app/collections/': typeof AuthenticatedAppCollectionsIndexRoute
  '/_authenticated/app/documents/': typeof AuthenticatedAppDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/app/assistant'
    | '/app/compare'
    | '/app/graph'
    | '/app/notes'
    | '/app/search'
    | '/app/upload'
    | '/app/'
    | '/app/collections/$id'
    | '/app/documents/$id'
    | '/app/collections/'
    | '/app/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/assistant'
    | '/app/compare'
    | '/app/graph'
    | '/app/notes'
    | '/app/search'
    | '/app/upload'
    | '/app'
    | '/app/collections/$id'
    | '/app/documents/$id'
    | '/app/collections'
    | '/app/documents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/assistant'
    | '/_authenticated/app/compare'
    | '/_authenticated/app/graph'
    | '/_authenticated/app/notes'
    | '/_authenticated/app/search'
    | '/_authenticated/app/upload'
    | '/_authenticated/app/'
    | '/_authenticated/app/collections/$id'
    | '/_authenticated/app/documents/$id'
    | '/_authenticated/app/collections/'
    | '/_authenticated/app/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assistant': {
      id: '/_authenticated/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AuthenticatedAppAssistantRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/compare': {
      id: '/_authenticated/app/compare'
      path: '/compare'
      fullPath: '/app/compare'
      preLoaderRoute: typeof AuthenticatedAppCompareRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/graph': {
      id: '/_authenticated/app/graph'
      path: '/graph'
      fullPath: '/app/graph'
      preLoaderRoute: typeof AuthenticatedAppGraphRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notes': {
      id: '/_authenticated/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AuthenticatedAppNotesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/search': {
      id: '/_authenticated/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AuthenticatedAppSearchRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/upload': {
      id: '/_authenticated/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AuthenticatedAppUploadRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/collections/': {
      id: '/_authenticated/app/collections/'
      path: '/collections'
      fullPath: '/app/collections/'
      preLoaderRoute: typeof AuthenticatedAppCollectionsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/collections/$id': {
      id: '/_authenticated/app/collections/$id'
      path: '/collections/$id'
      fullPath: '/app/collections/$id'
      preLoaderRoute: typeof AuthenticatedAppCollectionsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documents/': {
      id: '/_authenticated/app/documents/'
      path: '/documents'
      fullPath: '/app/documents/'
      preLoaderRoute: typeof AuthenticatedAppDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documents/$id': {
      id: '/_authenticated/app/documents/$id'
      path: '/documents/$id'
      fullPath: '/app/documents/$id'
      preLoaderRoute: typeof AuthenticatedAppDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAssistantRoute: typeof AuthenticatedAppAssistantRoute
  AuthenticatedAppCompareRoute: typeof AuthenticatedAppCompareRoute
  AuthenticatedAppGraphRoute: typeof AuthenticatedAppGraphRoute
  AuthenticatedAppNotesRoute: typeof AuthenticatedAppNotesRoute
  AuthenticatedAppSearchRoute: typeof AuthenticatedAppSearchRoute
  AuthenticatedAppUploadRoute: typeof AuthenticatedAppUploadRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCollectionsIdRoute: typeof AuthenticatedAppCollectionsIdRoute
  AuthenticatedAppDocumentsIdRoute: typeof AuthenticatedAppDocumentsIdRoute
  AuthenticatedAppCollectionsIndexRoute: typeof AuthenticatedAppCollectionsIndexRoute
  AuthenticatedAppDocumentsIndexRoute: typeof AuthenticatedAppDocumentsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAssistantRoute: AuthenticatedAppAssistantRoute,
  AuthenticatedAppCompareRoute: AuthenticatedAppCompareRoute,
  AuthenticatedAppGraphRoute: AuthenticatedAppGraphRoute,
  AuthenticatedAppNotesRoute: AuthenticatedAppNotesRoute,
  AuthenticatedAppSearchRoute: AuthenticatedAppSearchRoute,
  AuthenticatedAppUploadRoute: AuthenticatedAppUploadRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCollectionsIdRoute: AuthenticatedAppCollectionsIdRoute,
  AuthenticatedAppDocumentsIdRoute: AuthenticatedAppDocumentsIdRoute,
  AuthenticatedAppCollectionsIndexRoute: AuthenticatedAppCollectionsIndexRoute,
  AuthenticatedAppDocumentsIndexRoute: AuthenticatedAppDocumentsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
